# Generated by Django 3.2.11 on 2022-02-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20220203_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='egn',
            field=models.CharField(default='EGN', max_length=10, unique=True),
        ),
    ]
