# Generated by Django 3.2.12 on 2022-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('image_url', models.URLField(verbose_name='Link to Image')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
    ]
