# Generated by Django 3.2.12 on 2022-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('description', models.TextField(verbose_name='Description')),
                ('ingredients', models.CharField(max_length=250, verbose_name='Description')),
                ('time', models.IntegerField(verbose_name='Time {Minutes}')),
            ],
        ),
    ]
